### ISSUE TITLE
hocr-pdf forces "letter" size generating a white framing in pdfs

### ISSUE THREAD

**Issue by pprw** [stefan6419846/hocr-tools#35] opened 2024-11-07 14:01 UTC
hocr-pdf generates pdfs with a white framing

![image](https://github.com/user-attachments/assets/ac01e4be-6864-4efc-93e9-a269aa245b19)

I guess this is because hocr-pdf specifies `Page size:       612 x 792 pts (letter)` in metadata.

```
$ pdfinfo file_generated_by_hocr-pdf.pdf 
Title:           .
Subject:         unspecified
Keywords:        
Author:          anonymous
Creator:         hocr-tools
Producer:        ReportLab PDF Library - www.reportlab.com
CreationDate:    Thu Nov  7 16:37:25 2024 CET
ModDate:         Thu Nov  7 16:37:25 2024 CET
Custom Metadata: no
Metadata Stream: no
Tagged:          no
UserProperties:  no
Suspects:        no
Form:            none
JavaScript:      no
Pages:           74
Encrypted:       no
Page size:       612 x 792 pts (letter)
Page rot:        0
File size:       46620492 bytes
Optimized:       no
PDF version:     1.3
```

My workflow is to start with a pdf, extract images from it, use kraken and rebuild the pdf. 

The source pdf does not have the white frame and its pdfinfo output does not contain 'letter" as page size:
```
$ pdfinfo pdf_source.pdf 
Creator:         Utsushi 0.55.0
Producer:        GPL Ghostscript RELEASE CANDIDATE 1 9.28
CreationDate:    Fri Aug 30 13:39:36 2019 CEST
ModDate:         Fri Aug 30 13:39:36 2019 CEST
Custom Metadata: no
Metadata Stream: yes
Tagged:          no
UserProperties:  no
Suspects:        no
Form:            none
JavaScript:      no
Pages:           74
Encrypted:       no
Page size:       590 x 756 pts
Page rot:        0
File size:       12384016 bytes
Optimized:       no
PDF version:     1.5
```

I think the issue is related to the way I extract pages in jpeg from the source pdf. Indeed I did not encounter this problem when using pdfimages to do so (but I encountered [another issue](#34)).

Now I use this script to extract images from pdf the same way than what kraken does ([source](https://github.com/OpenITI/acdc_train/blob/e8c0020938ce4b12e37850b203c8842b1c1627f3/bin/pdf_images.py)

```python
#!/usr/bin/env python3
"""
A script splitting PDFs and converting them like eScriptorium.
"""
import os
import click
import json
import pyvips
from collections import defaultdict
from PIL import Image
from io import BytesIO

@click.command()
@click.option('-d', '--dpi', default=300, show_default=True,
              help='Output DPI.')
@click.option('-p', '--pattern', default='{0}_page_{1}.jpg', show_default=True,
              help='Pattern for filenames of individual pages.')
@click.option('-n', '--offset', default=1, show_default=True,
              help='Offset for file numbers.')
@click.argument('file')
def cli(dpi, pattern, offset, file):
    """
    A script splitting PDFs and converting them like eScriptorium.
    """
    doc = pyvips.Image.pdfload(file, n=-1, access='sequential')
    n_pages = doc.get('n-pages')
    for page_nb in range(n_pages):
        page = pyvips.Image.pdfload(file,
                                    page=page_nb,
                                    dpi=dpi,
                                    access='sequential')
        pdfname = os.path.basename(file)
        fname = pattern.format(pdfname, page_nb + offset)
        print(fname)
        page.write_to_file(fname)


if __name__ == '__main__':
    cli()
```

But I do not see the specification of "letter" format in the jpegs this script produces.
```

$ exiftool one_page_in_jpeg_extracted_from_pdf_source.jpg 
ExifTool Version Number         : 12.57
File Name                       : one_page_in_jpeg_extracted_from_pdf_source.jpg 
Directory                       : folder
File Size                       : 468 kB
File Modification Date/Time     : 2024:11:07 14:37:21+01:00
File Access Date/Time           : 2024:11:07 14:37:21+01:00
File Inode Change Date/Time     : 2024:11:07 14:37:25+01:00
File Permissions                : -rw-r--r--
File Type                       : JPEG
File Type Extension             : jpg
MIME Type                       : image/jpeg
Exif Byte Order                 : Little-endian (Intel, II)
Orientation                     : Horizontal (normal)
X Resolution                    : 300
Y Resolution                    : 300
Resolution Unit                 : inches
Y Cb Cr Positioning             : Centered
Exif Version                    : 0210
Components Configuration        : Y, Cb, Cr, -
Flashpix Version                : 0100
Color Space                     : Uncalibrated
Exif Image Width                : 2458
Exif Image Height               : 3150
Image Width                     : 2458
Image Height                    : 3150
Encoding Process                : Baseline DCT, Huffman coding
Bits Per Sample                 : 8
Color Components                : 3
Y Cb Cr Sub Sampling            : YCbCr4:2:0 (2 2)
Image Size                      : 2458x3150
Megapixels                      : 7.7

```

*So it seems hocr-tools adds incorrectly the information the ratio "612 x 792 pts (letter)" when it should be "590 x 756 pts".

**Comment by stefan6419846** [comment] 2024-11-07 14:16
Each page should adapt to the image size: https://github.com/stefan6419846/hocr-tools/blob/9970d378356d9623f1d44551c5ce84cbad61dede/hocr_tools_lib/tools/hocr_pdf.py#L94 Nevertheless, your example looks somehow odd as well, as it has more than one border.

Running the image from #34 through the following code (which corresponds to the image handling), I cannot reproduce the white border.

```python3
from PIL import Image
from reportlab.pdfgen.canvas import Canvas


images = ['bug_alignement.jpg']
pdf = Canvas('output.pdf', pageCompression=1)
pdf.setCreator('hocr-tools')
pdf.setTitle('directory')
dpi = 300
for image in images:
    im = Image.open(image)
    w, h = im.size
    try:
        dpi = im.info['dpi'][0]
    except KeyError:
        pass
    width = w * 72 / dpi
    height = h * 72 / dpi
    pdf.setPageSize((width, height))
    pdf.drawImage(image, 0, 0, width=width, height=height)
    pdf.showPage()
    im.close()
pdf.save()
```

Please make sure your input files are clean. Otherwise, please provide a way for me to reproduce this issue.

**Comment by pprw** [comment] 2024-11-07 15:31
The image in test files from #34 is generated by pdfimages, there is no white frame bug with these images.

Here are jpg and hocr files suitables for testing (jpg is generated by the script)
[white frame bug.zip](https://github.com/user-attachments/files/17663912/white.frame.bug.zip).

If you launch ` hocr-pdf --savefile output-kraken.pdf .` on these files, you should be able to reproduce the problem.

**Comment by stefan6419846** [comment] 2024-11-07 16:01
Thanks for the example. After some debugging, this should be fixed now: https://github.com/stefan6419846/hocr-tools/commit/a4b325c32bf26e5e1cc4cff0f9a7be293906135a

I am going to leave this issue open until I manage to create a corresponding unit/integration test to avoid accidentally breaking it again.

**Closed as completed** 2024-11-08 09:51 UTC
Labels: bug
